package com.enotion.Backend.enums;

public enum EventName {
    PING_CHECK,
    PONG_CHECK,

    CREATE_ROOM,
    JOIN_ROOM,
    LEAVE_ROOM,
    LEAVED_ROOM,
    DISSOLVE_ROOM,
    GET_ALL_ROOM,
    PLAYER_JOINED,
    START_GAME,
    STARTED_GAME,
    CHANGE_READY,

    JOIN_GAME,
    REJOIN_GAME,
    START_GAMEPLAY,
    PLAYER_CREATED,
    NEW_PLAYER_JOINED,
    PLAYER_QUIT,
    GAME_OVER,

    SEND_MESSAGE,
    RECEIVE_MESSAGE,

    SAVE_SCORE,
    SEND_SPAWN_POSITIONS,

    TIMEOUT_CONNECTION,

    // snake
    MOVE,
    SNAKE_MOVED,
    SNAKE_DIED,

    SPAWN_FOOD,
    SPAWN_POWER_UP,
    FOOD_EATEN,
    FOOD_REMOVED,
    POWER_UP_COLLECTED,
    POWER_UP_REMOVED,
    APPLY_EFFECT,

    TIMER_COUNT,
}
