export enum EventName {
  SELECTED_ROOM = "SELECTED_ROOM",
  CREATE_ROOM = "CREATE_ROOM",
  NEW_ROOM = "NEW_ROOM",
  UPDATE_ROOM = "UPDATE_ROOM",
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  GET_ALL_ROOM = "GET_ALL_ROOM",
  JOIN_ROOM_FAIL = "JOIN_ROOM_FAIL",

  MOVE = "MOVE",
  SNAKE_MOVED = "SNAKE_MOVED",
}
