export enum EventName {
  SELECTED_ROOM = "SELECTED_ROOM",
  CREATE_ROOM = "CREATE_ROOM",
  NEW_ROOM = "NEW_ROOM",
  UPDATE_ROOM = "UPDATE_ROOM",
  REMOVE_ROOM = "REMOVE_ROOM",
  DISSOLVE_ROOM = "DISSOLVE_ROOM",
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  LEAVED_ROOM = "LEAVED_ROOM",
  GET_ALL_ROOM = "GET_ALL_ROOM",
  JOIN_ROOM_FAIL = "JOIN_ROOM_FAIL",
  PLAYER_JOINED = "PLAYER_JOINED",

  MOVE = "MOVE",
  SNAKE_MOVED = "SNAKE_MOVED",
}
