export enum EventName {
  SELECTED_ROOM = "SELECTED_ROOM",
  CREATE_ROOM = "CREATE_ROOM",
  DISSOLVE_ROOM = "DISSOLVE_ROOM",
  JOIN_ROOM = "JOIN_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM",
  START_GAME = "START_GAME",
  STARTED_GAME = "STARTED_GAME",
  LEAVED_ROOM = "LEAVED_ROOM",
  GET_ALL_ROOM = "GET_ALL_ROOM",
  JOIN_ROOM_FAIL = "JOIN_ROOM_FAIL",
  PLAYER_JOINED = "PLAYER_JOINED",
  CHANGE_READY = "CHANGE_READY",

  START_GAMEPLAY = "START_GAMEPLAY",

  REJOIN_GAME = 'REJOIN_GAME',

  TIMEOUT_CONNECTION = "TIMEOUT_CONNECTION",

  SEND_MESSAGE = "SEND_MESSAGE",
  RECEIVE_MESSAGE = "RECEIVE_MESSAGE",

  MOVE = "MOVE",
  SNAKE_MOVED = "SNAKE_MOVED",


  DISCONNECT_NETWORK = "network:disconnected",
  RECONNECT_NETWORK = "network:reconnect",
}
